Revert "chore(backend): give a name to the postgres container used for testing"
This reverts commit 6265e2d4c34c0d6a71f8d5ae0a049ed8117407a0.

Due to reusing containers, I am getting errors like this:

```
com.github.dockerjava.api.exception.ConflictException: Status 409: {"message":"Conflict. The container name \"/contenttree-backend-test-db\" is already in use by container \"SOME-CONTAINER-ID\". You have to remove (or rename) that container to be able to reuse that name."}
```

Unless there is direct support for setting a common name prefix, it is not worth setting a custom
name.